steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build:refs"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["test", "--", "--coverage"]
  - name: "gcr.io/$PROJECT_ID/builder"
    entrypoint: bash
    args:
      [
        "./scripts/codecov-upload.bash",
        "$_CODECOV_TOKEN",
        "$COMMIT_SHA",
        "$BRANCH_NAME",
      ]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build:production"]
  - name: node:10.15.1
    entrypoint: npm
    dir: "functions"
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    dir: "functions"
    args: ["run", "build"]
