steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  # - name: node:10.15.1
  #   entrypoint: npm
  #   args: ["test"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build:refs"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build:production"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/timesheets", "."]
images:
  - "gcr.io/$PROJECT_ID/timesheets"
