steps:
  - name: "gcr.io/$PROJECT_ID/timesheets"

  - name: node:10.15.1
    entrypoint: npm
    args: ["--prefix", "functions", "install"]
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "--project", "$_FIREBASE_PROJECT_ID", "--token", "$_FIREBASE_TOKEN"]
